version: '3.5'
services:
    mysql:
        container_name: supsys_db
        image: mysql:8.0.33
        hostname: mysql
        restart: unless-stopped
        volumes:
            - /var/lib/mysql
        env_file:
            - .env.db
        networks:
        - supsys
    app:
        container_name: supsys_app
        build: .
        depends_on:
            - mysql
        hostname: app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8001:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        env_file:
            - .env
        volumes:
        - './.:/supsys'
        networks:
            - supsys

networks:
    supsys:
        driver: bridge
